mysql_db: SpringBootDB
mysql_db_user: nikos
mysql_db_password: nikos2002

mysql_user_home: /root
mysql_user_name: root
mysql_user_password: root
mysql_enabled_on_startup: true

mysql_databases:
    - name: "{{ mysql_db }}"

mysql_users:
    - name: "{{ mysql_db_user }}"
      host: "%"
      password: "{{ mysql_db_password }}"
      priv: "{{ mysql_db }}.*:ALL"

    - name: "{{ mysql_db_user }}"
      host: "localhost"
      password: "{{ mysql_db_password }}"
      priv: "{{ mysql_db }}.*:ALL"

    # - name: "{{ mysql_user_name }}"
    #   host: "%"
    #   password: "{{ mysql_user_password }}"
    #   priv: "*.*:ALL"

app:
    env:
        server.port: "{{ backend.port }}"
        spring.datasource.username: "{{ mysql_db_user}}"
        spring.datasource.password: "{{ mysql_db_password }}"
        spring.datasource.url: "jdbc:mysql://localhost:3306/{{ mysql_db }}"

    dir: "{{ ansible_user_dir }}/DistributedSystemsBackend"
    cmd: "java -jar target/DistributedSystemsAssignment-0.0.1-SNAPSHOT.jar"

