---
- hosts: backend_hosts
  pre_tasks:
    
    - name: Check if Docker is installed
      shell: docker --version && docker compose version
      register: docker_version_result
      ignore_errors: true

    - name: Set Docker installed fact
      set_fact:
        docker_installed: "{{ docker_version_result.rc == 0 }}"

    - name: if Docker is not installed, install it
      include_tasks: install_docker.yaml
      when: not docker_installed

    - name: Copy ssh key
      ansible.builtin.copy:
        src: "~/.ssh/id_distributed_systems_rsa"
        dest: "{{ ansible_user_dir }}/.ssh/id_distributed_systems_rsa"
      become: no

    - name: Set permissions
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.ssh/id_distributed_systems_rsa"
        mode: "0600"
      become: no

  tasks:
      - name: "Clone repo"
        ansible.builtin.git:
            repo: "git@github.com:NikosGour/DistributedSystemsFull.git"
            dest: "{{ app.docker_dir }}"
            version: main
            force: yes
            accept_hostkey: yes
            key_file: "{{ ansible_user_dir }}/.ssh/id_distributed_systems_rsa"

      - name: Update git submodules
        command: "git submodule update --init --recursive"
        args:
            chdir: "{{ app.docker_dir }}"

      - name: "Make .mvnw executable"
        file:
            path: "{{ app.docker_dir }}/backend/mvnw"
            mode: "u+x"

      - name: Down previous containers
        command: "docker compose down"
        args:
            chdir: "{{ app.docker_dir }}"
      
      - name: Run prerun script
        command: "./prerun.sh"
        args:
            chdir: "{{ app.docker_dir }}"

      - name: Build containers
        command: "docker compose build"
        args:
            chdir: "{{ app.docker_dir }}"

      - name: Up containers
        command: "docker compose up -d"
        args:
            chdir: "{{ app.docker_dir }}"